version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step3/
    overwites: yes
permissions:
  - object: /
    pattern: "**" # 모든 파일의 권한 설정
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh 
      timeout: 60 # 60 안에 실행, 60 뒤엔 배포 실패로 변경
      runas: ec2-user